pepitoapp/config/routes.rb
Rails.application.routes.draw do
  # resources :articles
  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'pages#hom'
  # get '/', to: "pages#home"

  # Este es el crud de songs
  # get '/songs', to: 'songs#index'
  # post '/songs', to: 'songs#create'
  # patch '/songs/:id', to: 'songs#update'
  # delete '/songs/:id', to: 'songs#destroy'
  # get '/songs/new', to: 'songs#new', as: 'new_song'
  # get '/songs/:id/edit', to: 'songs#edit', as: 'edit_song'
  # get 'songs/:id', to: 'songs#show', as: 'show_song'
  # show_song_url  songs/:id

  resources :artists do
    resources :songs
  end




end

pepitoapp/app/models/article.rb
class Article < ApplicationRecord
end

pepitoapp/app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  # def songs
  #   Song.where(id: self.artist_id)
  # end
end

pepitoapp/app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
end

pepitoapp/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

pepitoapp/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def new
  end

  def index
    @artists = Artist.all
  end

  def create
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

pepitoapp/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Accciones
  def home
  end
end

pepitoapp/app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    params[:query]
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    song = Song.new(song_params)
    if song.save
      redirect_to artist_song_path(song.artist, song)
    else
      render :new
    end
  end

  def edit
  end

  def destroy
  end

  def new
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new
  end

  private

    def song_params
      params.require(:song).permit(:title, :genre).merge(artist_id: params[:artist_id])
    end

end

pepitoapp/app/helpers/articles_helper.rb
module ArticlesHelper
end

pepitoapp/app/helpers/artists_helper.rb
module ArtistsHelper
end

pepitoapp/app/helpers/pages_helper.rb
module PagesHelper
end

pepitoapp/app/helpers/songs_helper.rb
module SongsHelper
end

pepitoapp/app/views/artists/create.html.erb
<h1>Artists#create</h1>
<p>Find me in app/views/artists/create.html.erb</p>

pepitoapp/app/views/artists/index.html.erb
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>

pepitoapp/app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

pepitoapp/app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<h2>Songs</h2>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= link_to song.title, artist_song_path(@artist, song) %></li>
  <% end %>
</ul>

<%= link_to "Crea song para #{@artist.name }", new_artist_song_path(@artist) %>

pepitoapp/app/views/songs/destroy.html.erb
<h1>Songs#destroy</h1>
<p>Find me in app/views/songs/destroy.html.erb</p>

pepitoapp/app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

pepitoapp/app/views/songs/index.html.erb
<ul>
  <% @songs.each do |song| %>
    <li><%= link_to song.title, show_song_path(song), {class: 'song', id: song.id} %></li>
  <% end %>
</ul>

<%= link_to 'Crea un song', new_song_path %>

pepitoapp/app/views/songs/new.html.erb
<!-- Embrace confusion -->

<h1>Crear una cancion para <%= @artist.name %></h1>

<!-- Se usa para formularios NO asociados a un modelo -->
<!-- form_tag(url_for_options = {}, options = {}, &block) -->
<%#= form_tag '/songs', method: :get do  %>
  <%#= text_field_tag 'query'%>
  <%#= submit_tag "Busca tu cancion" %>
<%# end %>

<!-- Se usa para formularios asociados a un modelo -->

<%= form_for [@artist, @song] do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :genre %>
  <%= f.submit "Crea tu cancion" %>
<% end %>




<!-- <form action="/"></form>
  <input type="hidden" name='_method' value='patch'>
  <input type="text" name='song[title]'>
  <input type="text" name='song[title]'>
  <input type="text" name='song[genre]'>
  <input type="submit" value='Crea la cancion'>
</form> -->

pepitoapp/app/views/songs/show.html.erb
<h1>Esta esla cancion <%= @song.title %></h1>

<p>escrita por <%= @song.artist.name %> del genero <%= @song.genre %></p>